name: Release
on:
  push:
    tags: 'v[0-9]+.[0-9]+.[0-9]+'
env:
  GOPROXY: https://proxy.golang.org
jobs:
  build:
    name: build
    runs-on: ubuntu-18.04
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Set up Go 1.16
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Setup tools
        run: make tools

      - name: make build-x
        run: make build-x

      - name: make release
        run: make release
